#!/bin/bash
set -u

VIRT_PATH_ROOT="/opt/virt"
VIRT_PATH_MACHINES="$VIRT_PATH_ROOT/machines"
VIRT_PATH_SYSTEMS="$VIRT_PATH_ROOT/os"
VIRT_PATH_SCRIPTS="$VIRT_PATH_ROOT/scripts"

VIRT_INSTALL_CPUS=1
VIRT_INSTALL_MEMORY=2048
VIRT_INSTALL_DISK=5
VIRT_INSTALL_GRAPHICS="vnc"

VIRT_POSTINSTALL_MEMORY=512

VIRT_INSTALL_REMOTE_CENTOS="http://mirrors.clouvider.net/CentOS/7/os/x86_64/"
