#!/bin/bash
set -x

if [ -n "$1" ]; then
	ip tunap add $1 mode tap user `whoami`
	ip link set $1 up
	sleep 0.5s
	ip link set labroot master $1
	exit 0
else
	echo "ERROR: No interface specified"
	exit 1
fi
